### recuperar todas las películas
GET http://localhost:1234/movies

### recuperar una película por id
GET http://localhost:1234/movies/241bf55d-b649-4109-af7c-0e6890ded3fc

### recuperar todas las peliculas por un género
GET http://localhost:1234/movies?genre=Action

### crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### eliminar una pelicula
DELETE http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Buscar peliculas por título

### Actualizar una pelicula
PATCH http://localhost:1234/movies/7d2832f8-c70a-410e-8963-4c93bf36cc9c
Content-Type: application/json

{
    "year": 1998
}

